#!/usr/bin/env bash

set -euo pipefail

readonly probe_host="${PLANK_PROBE_HOST:?Set PLANK_PROBE_HOST for the authorized test Host}"
readonly prepare_helper="${1:-/usr/libexec/plank/plank-display-prepare}"
readonly probe_config="${2:-/run/plank/headless-probe/plank-dual-1080.conf}"
readonly edid_dir="${3:-/usr/share/plank/display}"
readonly expected_monitor_count="${4:-2}"
readonly expected_screen_geometry="${5:-3840x1080}"
readonly nvfbc_probe="${6:-}"
readonly overlay_path=/etc/X11/xorg.conf.d/99-plank-headless.conf
readonly gdm_xauthority=/run/user/42/gdm/Xauthority
readonly generated_marker='# Generated by PLANK; do not edit.'

if [[ ${EUID} -ne 0 ]]; then
  echo "run-packaged-helper-probe.sh must run as root" >&2
  exit 1
fi
if [[ $(hostname -s) != "$probe_host" ]]; then
  echo "refusing to run the disruptive GDM probe outside ${probe_host}" >&2
  exit 1
fi
for required_path in "$prepare_helper" "$probe_config" \
  "${edid_dir}/virtual-1.edid" "${edid_dir}/virtual-2.edid"; do
  [[ -r $required_path ]] || {
    echo "missing packaged-helper probe input: ${required_path}" >&2
    exit 1
  }
done
if [[ -e $overlay_path || -L $overlay_path ]]; then
  echo "refusing to overwrite existing Xorg overlay: ${overlay_path}" >&2
  exit 1
fi
if ! systemctl is-active --quiet gdm.service; then
  echo "GDM must be active before the packaged-helper probe" >&2
  exit 1
fi

baseline_hash=$(sha256sum /etc/X11/xorg.conf)
cleanup() {
  set +e
  if [[ -f $overlay_path ]] &&
      head -n 1 -- "$overlay_path" | grep -Fxq -- "$generated_marker"; then
    rm -f -- "$overlay_path"
  fi
  systemctl restart gdm.service
}
trap cleanup EXIT INT TERM

systemctl stop gdm.service
"$prepare_helper" --config "$probe_config" --output "$overlay_path" \
  --edid-dir "$edid_dir"
systemctl start gdm.service

for _ in $(seq 1 30); do
  if [[ -S /tmp/.X11-unix/X0 && -r $gdm_xauthority ]]; then
    break
  fi
  sleep 1
done
if [[ ! -S /tmp/.X11-unix/X0 || ! -r $gdm_xauthority ]]; then
  systemctl status gdm.service --no-pager || true
  journalctl -u gdm.service --no-pager -n 180 || true
  echo "GDM did not start with the packaged PLANK overlay" >&2
  exit 1
fi

export DISPLAY=:0
export XAUTHORITY="$gdm_xauthority"
xrandr --listmonitors
xrandr --current
glxinfo -B

if [[ -n $nvfbc_probe ]]; then
  [[ -x $nvfbc_probe ]] || {
    echo "NvFBC probe is not executable: ${nvfbc_probe}" >&2
    exit 1
  }
  "$nvfbc_probe" --frames 120 --fps 60
fi

monitor_count=$(xrandr --listmonitors | awk 'NR == 1 {print $2}')
screen_geometry=$(xrandr --current | awk 'NR == 1 {print $8 "x" $10}' | tr -d ',')
[[ $monitor_count == "$expected_monitor_count" ]] || {
  echo "expected ${expected_monitor_count} RandR monitors, found ${monitor_count}" >&2
  exit 1
}
[[ $screen_geometry == "$expected_screen_geometry" ]] || {
  echo "expected ${expected_screen_geometry} screen, found ${screen_geometry}" >&2
  exit 1
}
[[ $(sha256sum /etc/X11/xorg.conf) == "$baseline_hash" ]] || {
  echo "the packaged helper modified the Autodesk Xorg baseline" >&2
  exit 1
}

echo "Packaged PLANK display helper probe: PASS"
