Section "ServerLayout"
    Identifier "PLANK KMS Shadow Test"
    Screen 0 "PLANK Screen"
EndSection

Section "ServerFlags"
    Option "AutoAddDevices" "true"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier "PLANK NVIDIA DRM"
    Driver "modesetting"
    BusID "PCI:81:0:0"
    Option "kmsdev" "/dev/dri/card0"
    Option "AccelMethod" "none"
    Option "PageFlip" "false"
EndSection

Section "Screen"
    Identifier "PLANK Screen"
    Device "PLANK NVIDIA DRM"
    DefaultDepth 30
    SubSection "Display"
        Depth 30
    EndSubSection
EndSection

