Section "ServerLayout"
    Identifier "StationConnect KMS Test"
    Screen 0 "StationConnect Screen"
EndSection

Section "ServerFlags"
    Option "AutoAddDevices" "true"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier "StationConnect NVIDIA DRM"
    Driver "modesetting"
    BusID "PCI:81:0:0"
    Option "kmsdev" "/dev/dri/card0"
    Option "AccelMethod" "glamor"
    Option "PageFlip" "true"
EndSection

Section "Screen"
    Identifier "StationConnect Screen"
    Device "StationConnect NVIDIA DRM"
    DefaultDepth 30
    SubSection "Display"
        Depth 30
    EndSubSection
EndSection

