#!/bin/sh

set -e

if [ "$1" = configure ] || [ "$1" = abort-upgrade ] || \
   [ "$1" = abort-deconfigure ] || [ "$1" = abort-remove ]; then
  if [ -z "${DPKG_ROOT:-}" ]; then
    if [ -x /usr/bin/udevadm ]; then
      /usr/bin/udevadm control --reload-rules || true
      /usr/bin/udevadm trigger --action=change \
        --subsystem-match=hidraw || true
      /usr/bin/udevadm trigger --action=change \
        --subsystem-match=input || true
    fi

    deb-systemd-helper --user unmask stationconnect-client.service \
      >/dev/null || true

    if deb-systemd-helper --quiet --user \
      was-enabled stationconnect-client.service; then
      deb-systemd-helper --user enable stationconnect-client.service \
        >/dev/null || true
    else
      deb-systemd-helper --user update-state stationconnect-client.service \
        >/dev/null || true
    fi
  fi
fi
