#!/bin/sh

set -e

if [ "$1" = purge ] && [ -z "${DPKG_ROOT:-}" ] && \
   [ -x /usr/bin/deb-systemd-helper ]; then
  deb-systemd-helper --user purge stationconnect-client.service \
    >/dev/null || true
fi
