#!/bin/sh

set -e

if { [ "$1" = remove ] || [ "$1" = purge ]; } && \
   [ -z "${DPKG_ROOT:-}" ] && \
   [ -x /usr/bin/udevadm ]; then
  /usr/bin/udevadm control --reload-rules || true
  /usr/bin/udevadm trigger --action=change \
    --subsystem-match=hidraw || true
  /usr/bin/udevadm trigger --action=change \
    --subsystem-match=input || true
fi
